spring:
    profiles:
        active: prod

---
# 开发环境配置
spring:
    profiles: dev
    application:
      name: eureka-server

server:
    port: 1111

eureka:
    instance:
        hostname: peer1
    client:
        #registerWithEureka: false
        #fetch-registry: false
        serviceUrl:
            defaultZone: http://peer2:1112/eureka/
            #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
# 测试环境配置
spring:
    profiles: test
    application:
      name: eureka-server

server:
    port: 1112

eureka:
    instance:
        hostname: peer2
    client:
        #registerWithEureka: false
        #fetch-registry: false
        serviceUrl:
            defaultZone: http://peer1:1111/eureka/
            #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
# 生产环境配置
spring:
    profiles: prod
    application:
      name: eureka-server

server:
    port: 1113

eureka:
    instance:
        hostname: peer3
    client:
        #registerWithEureka: false
        #fetch-registry: false
        serviceUrl:
            defaultZone: http://peer1:1111/eureka/
            #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/